const getActionTypes = () => ({
  CHECK_AUTHORIZATION: "CHECK_AUTHORIZATION",
  CHECK_AUTHORIZATION_SUCCESS: "CHECK_AUTHORIZATION_SUCCESS",
  CHECK_AUTHORIZATION_FAIL: "CHECK_AUTHORIZATION_FAIL",

  PLAYER_LOGIN: "PLAYER_LOGIN",
  PLAYER_LOGIN_SUCCESS: "PLAYER_LOGIN_SUCCESS",
  PLAYER_LOGIN_FAIL: "PLAYER_LOGIN_FAIL",

  PLAYER_LOGOUT: "PLAYER_LOGOUT",
  PLAYER_LOGOUT_SUCCESS: "PLAYER_LOGOUT",
  PLAYER_LOGOUT_FAIL: "PLAYER_LOGOUT",

  FETCH_ROOMS: "FETCH_ROOMS",
  FETCH_ROOMS_SUCCESS: "FETCH_ROOMS_SUCCESS",
  FETCH_ROOMS_FAIL: "FETCH_ROOMS_FAIL",

  CREATE_ROOM: "CREATE_ROOM",
  CREATE_ROOM_SUCCESS: "CREATE_ROOM_SUCCESS",
  CREATE_ROOM_FAIL: "CREATE_ROOM_FAIL",
});

export default getActionTypes;
